runtime: python311

# App Engine Standard environment for Flask applications
entrypoint: gunicorn -b :$PORT cineman.app:app --workers 2 --timeout 120

# Instance scaling configuration
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10

# Environment variables
# Note: For production, store sensitive data in Secret Manager instead of app.yaml
env_variables:
  DATABASE_URL: "${{ secrets.DATABASE_URL }}"
  GEMINI_API_KEY: "${{ secrets.GEMINI_API_KEY }}"
  TMDB_API_KEY: "${{ secrets.TMDB_API_KEY }}"
  OMDB_API_KEY: "${{ secrets.OMDB_API_KEY }}"

# Health check configuration
# App Engine will call /health endpoint to verify the app is running
handlers:
- url: /.*
  script: auto
  secure: always

# Enable API for monitoring
inbound_services:
- warmup
